In [ ]:
import numpy as np

01) Qual o comando para criar uma matriz NumPy de zeros de 3x4?

In [ ]:

matriz = np.zeros((3,4))
print(matriz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


02) Imprima o número de linhas e colunas de uma matriz usando NumPy.

In [ ]:
matriz.shape

(3, 4)

03) Defina o comando para acessar o elemento da linha 2 e coluna 3 de uma matriz NumPy denominada mat.

In [ ]:
mat = np.array([[1,2,3,4],
               [4,3,2,1],
               [6,7,8,9]])
print(mat)

print(mat[2][3])

[[1 2 3 4]
 [4 3 2 1]
 [6 7 8 9]]
9


04) Crie um array com os seguintes valores [2,3,4,5,6,7].

In [ ]:
array = np.array([2,3,4,5,6,7])
print(array)

[2 3 4 5 6 7]


05) Dada a seguinte matriz arrayA, qual o índice do elemento '2g'?
arrayA = np.array( [
                   ['1a','1b','1c','1d','1e','1f','1g','1h','1i'],
                   ['2a','2b','2c','2d','2e','2f','2g','2h','2i'],
                   ['3a','3b','3c','3d','3e','3f','3g','3h','3i'],
                   ['4a','4b','4c','4d','4e','4f','4g', '4h','4i']
                   ])

                   **Resposta:** Coluna ---> 1
                             Linha  ---> 6

06) Dada a seguinte array a = ['2a' '2b' '2c' '2d' '2e' '2f' '2g' '2h' '2i']


a) Como posso imprimir a seguinte fatia, ['2a' '2b' '2c' '2d' '2e']?
b) Como posso imprimir a seguinte fatia, ['2i']?
c) Como posso imprimir a seguinte fatia, ['2a' '2c' '2e' '2g' '2i']?
d) Como posso imprimir a seguinte fatia, ['2h' '2g' '2f']?

In [ ]:
a = np.array(['2a','2b','2c','2d','2e','2f','2g','2h','2i'])
print(a)

print(a[0:5])
print(a[8])
print(a[0:10:2])
print(a[-2:-5])

['2a' '2b' '2c' '2d' '2e' '2f' '2g' '2h' '2i']
['2a' '2b' '2c' '2d' '2e']
2i
['2a' '2c' '2e' '2g' '2i']
[]


07) Crie uma matriz booleana numpy 3×3 com ‘True’

In [ ]:
matriz_booleana = np.ones((3,3), dtype = bool)


print(matriz_booleana)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


08) Dada a seguinte matriz arr, imprima todos os valores ímpares.
arr = np.arange(10)

In [ ]:
arr = np.arange(10)
print(arr)
print(arr[1:10:2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


09) Transforme uma matriz arr de uma dimensão de 12 elementos num matriz de 3x4.

In [ ]:
arr = np.arange(12)
print(arr)


arr_novo = arr.reshape(3,4)
print(arr_novo)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


10) Crie uma matriz identidade de 4x4.

In [ ]:
matriz_identidade = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])
print(matriz_identidade)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
